//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatCallback extends com.zeroc.Ice.Object
{
    void onNewMessage(Message msg, com.zeroc.Ice.Current current);

    void onUserStatusChanged(User user, com.zeroc.Ice.Current current);

    void onGroupMemberAdded(String groupName, String username, com.zeroc.Ice.Current current);

    void onVoiceNoteReceived(String from, String to, byte[] audioData, boolean isGroup, com.zeroc.Ice.Current current);

    void onIncomingCall(String from, com.zeroc.Ice.Current current);

    void onWebRTCSignal(String from, String signalType, String signalData, com.zeroc.Ice.Current current);

    void onICECandidate(String from, String candidate, com.zeroc.Ice.Current current);

    void onCallEnded(String from, com.zeroc.Ice.Current current);

    void onAudioChunk(String from, byte[] audioData, com.zeroc.Ice.Current current);

    void onCallAccepted(String from, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Chat::ChatCallback",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Chat::ChatCallback";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onNewMessage(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Message iceP_msg;
        iceP_msg = Message.ice_read(istr);
        inS.endReadParams();
        obj.onNewMessage(iceP_msg, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onUserStatusChanged(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        User iceP_user;
        iceP_user = User.ice_read(istr);
        inS.endReadParams();
        obj.onUserStatusChanged(iceP_user, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onGroupMemberAdded(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_username;
        iceP_groupName = istr.readString();
        iceP_username = istr.readString();
        inS.endReadParams();
        obj.onGroupMemberAdded(iceP_groupName, iceP_username, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onVoiceNoteReceived(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        byte[] iceP_audioData;
        boolean iceP_isGroup;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_audioData = istr.readByteSeq();
        iceP_isGroup = istr.readBool();
        inS.endReadParams();
        obj.onVoiceNoteReceived(iceP_from, iceP_to, iceP_audioData, iceP_isGroup, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onIncomingCall(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        iceP_from = istr.readString();
        inS.endReadParams();
        obj.onIncomingCall(iceP_from, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onWebRTCSignal(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_signalType;
        String iceP_signalData;
        iceP_from = istr.readString();
        iceP_signalType = istr.readString();
        iceP_signalData = istr.readString();
        inS.endReadParams();
        obj.onWebRTCSignal(iceP_from, iceP_signalType, iceP_signalData, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onICECandidate(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_candidate;
        iceP_from = istr.readString();
        iceP_candidate = istr.readString();
        inS.endReadParams();
        obj.onICECandidate(iceP_from, iceP_candidate, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onCallEnded(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        iceP_from = istr.readString();
        inS.endReadParams();
        obj.onCallEnded(iceP_from, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onAudioChunk(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        byte[] iceP_audioData;
        iceP_from = istr.readString();
        iceP_audioData = istr.readByteSeq();
        inS.endReadParams();
        obj.onAudioChunk(iceP_from, iceP_audioData, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onCallAccepted(ChatCallback obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        iceP_from = istr.readString();
        inS.endReadParams();
        obj.onCallAccepted(iceP_from, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "onAudioChunk",
        "onCallAccepted",
        "onCallEnded",
        "onGroupMemberAdded",
        "onICECandidate",
        "onIncomingCall",
        "onNewMessage",
        "onUserStatusChanged",
        "onVoiceNoteReceived",
        "onWebRTCSignal"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 4:
            {
                return _iceD_onAudioChunk(this, in, current);
            }
            case 5:
            {
                return _iceD_onCallAccepted(this, in, current);
            }
            case 6:
            {
                return _iceD_onCallEnded(this, in, current);
            }
            case 7:
            {
                return _iceD_onGroupMemberAdded(this, in, current);
            }
            case 8:
            {
                return _iceD_onICECandidate(this, in, current);
            }
            case 9:
            {
                return _iceD_onIncomingCall(this, in, current);
            }
            case 10:
            {
                return _iceD_onNewMessage(this, in, current);
            }
            case 11:
            {
                return _iceD_onUserStatusChanged(this, in, current);
            }
            case 12:
            {
                return _iceD_onVoiceNoteReceived(this, in, current);
            }
            case 13:
            {
                return _iceD_onWebRTCSignal(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
