//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatCallbackPrx extends com.zeroc.Ice.ObjectPrx
{
    default void onNewMessage(Message msg)
    {
        onNewMessage(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onNewMessage(Message msg, java.util.Map<String, String> context)
    {
        _iceI_onNewMessageAsync(msg, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onNewMessageAsync(Message msg)
    {
        return _iceI_onNewMessageAsync(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onNewMessageAsync(Message msg, java.util.Map<String, String> context)
    {
        return _iceI_onNewMessageAsync(msg, context, false);
    }

    /**
     * @hidden
     * @param iceP_msg -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onNewMessageAsync(Message iceP_msg, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onNewMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Message.ice_write(ostr, iceP_msg);
                 }, null);
        return f;
    }

    default void onUserStatusChanged(User user)
    {
        onUserStatusChanged(user, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onUserStatusChanged(User user, java.util.Map<String, String> context)
    {
        _iceI_onUserStatusChangedAsync(user, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onUserStatusChangedAsync(User user)
    {
        return _iceI_onUserStatusChangedAsync(user, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onUserStatusChangedAsync(User user, java.util.Map<String, String> context)
    {
        return _iceI_onUserStatusChangedAsync(user, context, false);
    }

    /**
     * @hidden
     * @param iceP_user -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onUserStatusChangedAsync(User iceP_user, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onUserStatusChanged", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     User.ice_write(ostr, iceP_user);
                 }, null);
        return f;
    }

    default void onGroupMemberAdded(String groupName, String username)
    {
        onGroupMemberAdded(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onGroupMemberAdded(String groupName, String username, java.util.Map<String, String> context)
    {
        _iceI_onGroupMemberAddedAsync(groupName, username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onGroupMemberAddedAsync(String groupName, String username)
    {
        return _iceI_onGroupMemberAddedAsync(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onGroupMemberAddedAsync(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_onGroupMemberAddedAsync(groupName, username, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onGroupMemberAddedAsync(String iceP_groupName, String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onGroupMemberAdded", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_username);
                 }, null);
        return f;
    }

    default void onVoiceNoteReceived(String from, String to, byte[] audioData, boolean isGroup)
    {
        onVoiceNoteReceived(from, to, audioData, isGroup, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onVoiceNoteReceived(String from, String to, byte[] audioData, boolean isGroup, java.util.Map<String, String> context)
    {
        _iceI_onVoiceNoteReceivedAsync(from, to, audioData, isGroup, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onVoiceNoteReceivedAsync(String from, String to, byte[] audioData, boolean isGroup)
    {
        return _iceI_onVoiceNoteReceivedAsync(from, to, audioData, isGroup, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onVoiceNoteReceivedAsync(String from, String to, byte[] audioData, boolean isGroup, java.util.Map<String, String> context)
    {
        return _iceI_onVoiceNoteReceivedAsync(from, to, audioData, isGroup, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_audioData -
     * @param iceP_isGroup -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onVoiceNoteReceivedAsync(String iceP_from, String iceP_to, byte[] iceP_audioData, boolean iceP_isGroup, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onVoiceNoteReceived", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeByteSeq(iceP_audioData);
                     ostr.writeBool(iceP_isGroup);
                 }, null);
        return f;
    }

    default void onIncomingCall(String from)
    {
        onIncomingCall(from, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onIncomingCall(String from, java.util.Map<String, String> context)
    {
        _iceI_onIncomingCallAsync(from, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onIncomingCallAsync(String from)
    {
        return _iceI_onIncomingCallAsync(from, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onIncomingCallAsync(String from, java.util.Map<String, String> context)
    {
        return _iceI_onIncomingCallAsync(from, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onIncomingCallAsync(String iceP_from, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onIncomingCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                 }, null);
        return f;
    }

    default void onWebRTCSignal(String from, String signalType, String signalData)
    {
        onWebRTCSignal(from, signalType, signalData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onWebRTCSignal(String from, String signalType, String signalData, java.util.Map<String, String> context)
    {
        _iceI_onWebRTCSignalAsync(from, signalType, signalData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onWebRTCSignalAsync(String from, String signalType, String signalData)
    {
        return _iceI_onWebRTCSignalAsync(from, signalType, signalData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onWebRTCSignalAsync(String from, String signalType, String signalData, java.util.Map<String, String> context)
    {
        return _iceI_onWebRTCSignalAsync(from, signalType, signalData, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_signalType -
     * @param iceP_signalData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onWebRTCSignalAsync(String iceP_from, String iceP_signalType, String iceP_signalData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onWebRTCSignal", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_signalType);
                     ostr.writeString(iceP_signalData);
                 }, null);
        return f;
    }

    default void onICECandidate(String from, String candidate)
    {
        onICECandidate(from, candidate, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onICECandidate(String from, String candidate, java.util.Map<String, String> context)
    {
        _iceI_onICECandidateAsync(from, candidate, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onICECandidateAsync(String from, String candidate)
    {
        return _iceI_onICECandidateAsync(from, candidate, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onICECandidateAsync(String from, String candidate, java.util.Map<String, String> context)
    {
        return _iceI_onICECandidateAsync(from, candidate, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_candidate -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onICECandidateAsync(String iceP_from, String iceP_candidate, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onICECandidate", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_candidate);
                 }, null);
        return f;
    }

    default void onCallEnded(String from)
    {
        onCallEnded(from, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onCallEnded(String from, java.util.Map<String, String> context)
    {
        _iceI_onCallEndedAsync(from, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onCallEndedAsync(String from)
    {
        return _iceI_onCallEndedAsync(from, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onCallEndedAsync(String from, java.util.Map<String, String> context)
    {
        return _iceI_onCallEndedAsync(from, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onCallEndedAsync(String iceP_from, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onCallEnded", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                 }, null);
        return f;
    }

    default void onAudioChunk(String from, byte[] audioData)
    {
        onAudioChunk(from, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onAudioChunk(String from, byte[] audioData, java.util.Map<String, String> context)
    {
        _iceI_onAudioChunkAsync(from, audioData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onAudioChunkAsync(String from, byte[] audioData)
    {
        return _iceI_onAudioChunkAsync(from, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onAudioChunkAsync(String from, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_onAudioChunkAsync(from, audioData, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_audioData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onAudioChunkAsync(String iceP_from, byte[] iceP_audioData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onAudioChunk", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeByteSeq(iceP_audioData);
                 }, null);
        return f;
    }

    default void onCallAccepted(String from)
    {
        onCallAccepted(from, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onCallAccepted(String from, java.util.Map<String, String> context)
    {
        _iceI_onCallAcceptedAsync(from, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onCallAcceptedAsync(String from)
    {
        return _iceI_onCallAcceptedAsync(from, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onCallAcceptedAsync(String from, java.util.Map<String, String> context)
    {
        return _iceI_onCallAcceptedAsync(from, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onCallAcceptedAsync(String iceP_from, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onCallAccepted", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatCallbackPrx.class, _ChatCallbackPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatCallbackPrx.class, _ChatCallbackPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatCallbackPrx.class, _ChatCallbackPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatCallbackPrx.class, _ChatCallbackPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatCallbackPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatCallbackPrx.class, _ChatCallbackPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatCallbackPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatCallbackPrx.class, _ChatCallbackPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatCallbackPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatCallbackPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatCallbackPrx ice_adapterId(String newAdapterId)
    {
        return (ChatCallbackPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatCallbackPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatCallbackPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatCallbackPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatCallbackPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatCallbackPrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatCallbackPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatCallbackPrx ice_connectionCached(boolean newCache)
    {
        return (ChatCallbackPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatCallbackPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatCallbackPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatCallbackPrx ice_secure(boolean b)
    {
        return (ChatCallbackPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatCallbackPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatCallbackPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatCallbackPrx ice_preferSecure(boolean b)
    {
        return (ChatCallbackPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatCallbackPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatCallbackPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatCallbackPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatCallbackPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatCallbackPrx ice_collocationOptimized(boolean b)
    {
        return (ChatCallbackPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatCallbackPrx ice_twoway()
    {
        return (ChatCallbackPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatCallbackPrx ice_oneway()
    {
        return (ChatCallbackPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatCallbackPrx ice_batchOneway()
    {
        return (ChatCallbackPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatCallbackPrx ice_datagram()
    {
        return (ChatCallbackPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatCallbackPrx ice_batchDatagram()
    {
        return (ChatCallbackPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatCallbackPrx ice_compress(boolean co)
    {
        return (ChatCallbackPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatCallbackPrx ice_timeout(int t)
    {
        return (ChatCallbackPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatCallbackPrx ice_connectionId(String connectionId)
    {
        return (ChatCallbackPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatCallbackPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatCallbackPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Chat::ChatCallback";
    }
}
