//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatService extends com.zeroc.Ice.Object
{
    Response login(String username, ChatCallbackPrx callback, com.zeroc.Ice.Current current);

    Response logout(String username, com.zeroc.Ice.Current current);

    String[] getOnlineUsers(com.zeroc.Ice.Current current);

    java.util.Map<java.lang.String, java.lang.Boolean> getAllUsers(com.zeroc.Ice.Current current);

    Response sendMessageToUser(String from, String to, String content, com.zeroc.Ice.Current current);

    Response sendMessageToGroup(String from, String groupName, String content, com.zeroc.Ice.Current current);

    Message[] getPendingMessages(String username, com.zeroc.Ice.Current current);

    Response createGroup(String groupName, String creator, com.zeroc.Ice.Current current);

    Response addToGroup(String groupName, String username, com.zeroc.Ice.Current current);

    String[] getGroups(com.zeroc.Ice.Current current);

    String[] getUserGroups(String username, com.zeroc.Ice.Current current);

    String[] getGroupMembers(String groupName, com.zeroc.Ice.Current current);

    String[] getHistory(String username, com.zeroc.Ice.Current current);

    Response sendVoiceNoteToUser(String from, String to, byte[] audioData, com.zeroc.Ice.Current current);

    Response sendVoiceNoteToGroup(String from, String groupName, byte[] audioData, com.zeroc.Ice.Current current);

    Response initiateCall(String from, String to, com.zeroc.Ice.Current current);

    Response sendWebRTCSignal(String from, String to, String signalType, String signalData, com.zeroc.Ice.Current current);

    Response sendICECandidate(String from, String to, String candidate, com.zeroc.Ice.Current current);

    Response endCall(String from, String to, com.zeroc.Ice.Current current);

    Response sendAudioChunk(String from, String to, byte[] audioData, com.zeroc.Ice.Current current);

    Response acceptCall(String from, String to, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Chat::ChatService",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Chat::ChatService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_login(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        ChatCallbackPrx iceP_callback;
        iceP_username = istr.readString();
        iceP_callback = ChatCallbackPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        Response ret = obj.login(iceP_username, iceP_callback, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_logout(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        Response ret = obj.logout(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getOnlineUsers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getOnlineUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllUsers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        java.util.Map<java.lang.String, java.lang.Boolean> ret = obj.getAllUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        UserStatusMapHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendMessageToUser(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        String iceP_content;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_content = istr.readString();
        inS.endReadParams();
        Response ret = obj.sendMessageToUser(iceP_from, iceP_to, iceP_content, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendMessageToGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_groupName;
        String iceP_content;
        iceP_from = istr.readString();
        iceP_groupName = istr.readString();
        iceP_content = istr.readString();
        inS.endReadParams();
        Response ret = obj.sendMessageToGroup(iceP_from, iceP_groupName, iceP_content, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPendingMessages(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        Message[] ret = obj.getPendingMessages(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_creator;
        iceP_groupName = istr.readString();
        iceP_creator = istr.readString();
        inS.endReadParams();
        Response ret = obj.createGroup(iceP_groupName, iceP_creator, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_addToGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_username;
        iceP_groupName = istr.readString();
        iceP_username = istr.readString();
        inS.endReadParams();
        Response ret = obj.addToGroup(iceP_groupName, iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroups(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getGroups(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getUserGroups(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getUserGroups(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroupMembers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        iceP_groupName = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getGroupMembers(iceP_groupName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getHistory(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendVoiceNoteToUser(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        byte[] iceP_audioData;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_audioData = istr.readByteSeq();
        inS.endReadParams();
        Response ret = obj.sendVoiceNoteToUser(iceP_from, iceP_to, iceP_audioData, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendVoiceNoteToGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_groupName;
        byte[] iceP_audioData;
        iceP_from = istr.readString();
        iceP_groupName = istr.readString();
        iceP_audioData = istr.readByteSeq();
        inS.endReadParams();
        Response ret = obj.sendVoiceNoteToGroup(iceP_from, iceP_groupName, iceP_audioData, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_initiateCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        inS.endReadParams();
        Response ret = obj.initiateCall(iceP_from, iceP_to, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendWebRTCSignal(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        String iceP_signalType;
        String iceP_signalData;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_signalType = istr.readString();
        iceP_signalData = istr.readString();
        inS.endReadParams();
        Response ret = obj.sendWebRTCSignal(iceP_from, iceP_to, iceP_signalType, iceP_signalData, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendICECandidate(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        String iceP_candidate;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_candidate = istr.readString();
        inS.endReadParams();
        Response ret = obj.sendICECandidate(iceP_from, iceP_to, iceP_candidate, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_endCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        inS.endReadParams();
        Response ret = obj.endCall(iceP_from, iceP_to, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudioChunk(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        byte[] iceP_audioData;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        iceP_audioData = istr.readByteSeq();
        inS.endReadParams();
        Response ret = obj.sendAudioChunk(iceP_from, iceP_to, iceP_audioData, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_acceptCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        inS.endReadParams();
        Response ret = obj.acceptCall(iceP_from, iceP_to, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Response.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "acceptCall",
        "addToGroup",
        "createGroup",
        "endCall",
        "getAllUsers",
        "getGroupMembers",
        "getGroups",
        "getHistory",
        "getOnlineUsers",
        "getPendingMessages",
        "getUserGroups",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "initiateCall",
        "login",
        "logout",
        "sendAudioChunk",
        "sendICECandidate",
        "sendMessageToGroup",
        "sendMessageToUser",
        "sendVoiceNoteToGroup",
        "sendVoiceNoteToUser",
        "sendWebRTCSignal"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_acceptCall(this, in, current);
            }
            case 1:
            {
                return _iceD_addToGroup(this, in, current);
            }
            case 2:
            {
                return _iceD_createGroup(this, in, current);
            }
            case 3:
            {
                return _iceD_endCall(this, in, current);
            }
            case 4:
            {
                return _iceD_getAllUsers(this, in, current);
            }
            case 5:
            {
                return _iceD_getGroupMembers(this, in, current);
            }
            case 6:
            {
                return _iceD_getGroups(this, in, current);
            }
            case 7:
            {
                return _iceD_getHistory(this, in, current);
            }
            case 8:
            {
                return _iceD_getOnlineUsers(this, in, current);
            }
            case 9:
            {
                return _iceD_getPendingMessages(this, in, current);
            }
            case 10:
            {
                return _iceD_getUserGroups(this, in, current);
            }
            case 11:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 12:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 13:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 14:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 15:
            {
                return _iceD_initiateCall(this, in, current);
            }
            case 16:
            {
                return _iceD_login(this, in, current);
            }
            case 17:
            {
                return _iceD_logout(this, in, current);
            }
            case 18:
            {
                return _iceD_sendAudioChunk(this, in, current);
            }
            case 19:
            {
                return _iceD_sendICECandidate(this, in, current);
            }
            case 20:
            {
                return _iceD_sendMessageToGroup(this, in, current);
            }
            case 21:
            {
                return _iceD_sendMessageToUser(this, in, current);
            }
            case 22:
            {
                return _iceD_sendVoiceNoteToGroup(this, in, current);
            }
            case 23:
            {
                return _iceD_sendVoiceNoteToUser(this, in, current);
            }
            case 24:
            {
                return _iceD_sendWebRTCSignal(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
