//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default Response login(String username, ChatCallbackPrx callback)
    {
        return login(username, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response login(String username, ChatCallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_loginAsync(username, callback, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> loginAsync(String username, ChatCallbackPrx callback)
    {
        return _iceI_loginAsync(username, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> loginAsync(String username, ChatCallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_loginAsync(username, callback, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_callback -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_loginAsync(String iceP_username, ChatCallbackPrx iceP_callback, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "login", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeProxy(iceP_callback);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response logout(String username)
    {
        return logout(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response logout(String username, java.util.Map<String, String> context)
    {
        return _iceI_logoutAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> logoutAsync(String username)
    {
        return _iceI_logoutAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> logoutAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_logoutAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_logoutAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "logout", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default String[] getOnlineUsers()
    {
        return getOnlineUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getOnlineUsers(java.util.Map<String, String> context)
    {
        return _iceI_getOnlineUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getOnlineUsersAsync()
    {
        return _iceI_getOnlineUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getOnlineUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getOnlineUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getOnlineUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getOnlineUsers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default java.util.Map<java.lang.String, java.lang.Boolean> getAllUsers()
    {
        return getAllUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.Map<java.lang.String, java.lang.Boolean> getAllUsers(java.util.Map<String, String> context)
    {
        return _iceI_getAllUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<java.lang.String, java.lang.Boolean>> getAllUsersAsync()
    {
        return _iceI_getAllUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<java.lang.String, java.lang.Boolean>> getAllUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.util.Map<java.lang.String, java.lang.Boolean>> _iceI_getAllUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.Map<java.lang.String, java.lang.Boolean>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllUsers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     java.util.Map<java.lang.String, java.lang.Boolean> ret;
                     ret = UserStatusMapHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Response sendMessageToUser(String from, String to, String content)
    {
        return sendMessageToUser(from, to, content, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response sendMessageToUser(String from, String to, String content, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageToUserAsync(from, to, content, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> sendMessageToUserAsync(String from, String to, String content)
    {
        return _iceI_sendMessageToUserAsync(from, to, content, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> sendMessageToUserAsync(String from, String to, String content, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageToUserAsync(from, to, content, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_content -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_sendMessageToUserAsync(String iceP_from, String iceP_to, String iceP_content, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessageToUser", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_content);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response sendMessageToGroup(String from, String groupName, String content)
    {
        return sendMessageToGroup(from, groupName, content, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response sendMessageToGroup(String from, String groupName, String content, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageToGroupAsync(from, groupName, content, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> sendMessageToGroupAsync(String from, String groupName, String content)
    {
        return _iceI_sendMessageToGroupAsync(from, groupName, content, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> sendMessageToGroupAsync(String from, String groupName, String content, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageToGroupAsync(from, groupName, content, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_groupName -
     * @param iceP_content -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_sendMessageToGroupAsync(String iceP_from, String iceP_groupName, String iceP_content, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessageToGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_content);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Message[] getPendingMessages(String username)
    {
        return getPendingMessages(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Message[] getPendingMessages(String username, java.util.Map<String, String> context)
    {
        return _iceI_getPendingMessagesAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Message[]> getPendingMessagesAsync(String username)
    {
        return _iceI_getPendingMessagesAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Message[]> getPendingMessagesAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_getPendingMessagesAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Message[]> _iceI_getPendingMessagesAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Message[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPendingMessages", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     Message[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Response createGroup(String groupName, String creator)
    {
        return createGroup(groupName, creator, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response createGroup(String groupName, String creator, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creator, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> createGroupAsync(String groupName, String creator)
    {
        return _iceI_createGroupAsync(groupName, creator, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> createGroupAsync(String groupName, String creator, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creator, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_creator -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_createGroupAsync(String iceP_groupName, String iceP_creator, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_creator);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response addToGroup(String groupName, String username)
    {
        return addToGroup(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response addToGroup(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_addToGroupAsync(groupName, username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> addToGroupAsync(String groupName, String username)
    {
        return _iceI_addToGroupAsync(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> addToGroupAsync(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_addToGroupAsync(groupName, username, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_addToGroupAsync(String iceP_groupName, String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addToGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default String[] getGroups()
    {
        return getGroups(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getGroups(java.util.Map<String, String> context)
    {
        return _iceI_getGroupsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getGroupsAsync()
    {
        return _iceI_getGroupsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getGroupsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getGroupsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getGroupsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroups", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default String[] getUserGroups(String username)
    {
        return getUserGroups(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getUserGroups(String username, java.util.Map<String, String> context)
    {
        return _iceI_getUserGroupsAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getUserGroupsAsync(String username)
    {
        return _iceI_getUserGroupsAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getUserGroupsAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_getUserGroupsAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getUserGroupsAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getUserGroups", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default String[] getGroupMembers(String groupName)
    {
        return getGroupMembers(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getGroupMembers(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupMembersAsync(groupName, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getGroupMembersAsync(String groupName)
    {
        return _iceI_getGroupMembersAsync(groupName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getGroupMembersAsync(String groupName, java.util.Map<String, String> context)
    {
        return _iceI_getGroupMembersAsync(groupName, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getGroupMembersAsync(String iceP_groupName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroupMembers", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default String[] getHistory(String username)
    {
        return getHistory(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getHistory(String username, java.util.Map<String, String> context)
    {
        return _iceI_getHistoryAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getHistoryAsync(String username)
    {
        return _iceI_getHistoryAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getHistoryAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_getHistoryAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getHistoryAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getHistory", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default Response sendVoiceNoteToUser(String from, String to, byte[] audioData)
    {
        return sendVoiceNoteToUser(from, to, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response sendVoiceNoteToUser(String from, String to, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteToUserAsync(from, to, audioData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> sendVoiceNoteToUserAsync(String from, String to, byte[] audioData)
    {
        return _iceI_sendVoiceNoteToUserAsync(from, to, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> sendVoiceNoteToUserAsync(String from, String to, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteToUserAsync(from, to, audioData, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_audioData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_sendVoiceNoteToUserAsync(String iceP_from, String iceP_to, byte[] iceP_audioData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceNoteToUser", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeByteSeq(iceP_audioData);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response sendVoiceNoteToGroup(String from, String groupName, byte[] audioData)
    {
        return sendVoiceNoteToGroup(from, groupName, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response sendVoiceNoteToGroup(String from, String groupName, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteToGroupAsync(from, groupName, audioData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> sendVoiceNoteToGroupAsync(String from, String groupName, byte[] audioData)
    {
        return _iceI_sendVoiceNoteToGroupAsync(from, groupName, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> sendVoiceNoteToGroupAsync(String from, String groupName, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceNoteToGroupAsync(from, groupName, audioData, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_groupName -
     * @param iceP_audioData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_sendVoiceNoteToGroupAsync(String iceP_from, String iceP_groupName, byte[] iceP_audioData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceNoteToGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_groupName);
                     ostr.writeByteSeq(iceP_audioData);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response initiateCall(String from, String to)
    {
        return initiateCall(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response initiateCall(String from, String to, java.util.Map<String, String> context)
    {
        return _iceI_initiateCallAsync(from, to, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> initiateCallAsync(String from, String to)
    {
        return _iceI_initiateCallAsync(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> initiateCallAsync(String from, String to, java.util.Map<String, String> context)
    {
        return _iceI_initiateCallAsync(from, to, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_initiateCallAsync(String iceP_from, String iceP_to, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "initiateCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response sendWebRTCSignal(String from, String to, String signalType, String signalData)
    {
        return sendWebRTCSignal(from, to, signalType, signalData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response sendWebRTCSignal(String from, String to, String signalType, String signalData, java.util.Map<String, String> context)
    {
        return _iceI_sendWebRTCSignalAsync(from, to, signalType, signalData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> sendWebRTCSignalAsync(String from, String to, String signalType, String signalData)
    {
        return _iceI_sendWebRTCSignalAsync(from, to, signalType, signalData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> sendWebRTCSignalAsync(String from, String to, String signalType, String signalData, java.util.Map<String, String> context)
    {
        return _iceI_sendWebRTCSignalAsync(from, to, signalType, signalData, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_signalType -
     * @param iceP_signalData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_sendWebRTCSignalAsync(String iceP_from, String iceP_to, String iceP_signalType, String iceP_signalData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendWebRTCSignal", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_signalType);
                     ostr.writeString(iceP_signalData);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response sendICECandidate(String from, String to, String candidate)
    {
        return sendICECandidate(from, to, candidate, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response sendICECandidate(String from, String to, String candidate, java.util.Map<String, String> context)
    {
        return _iceI_sendICECandidateAsync(from, to, candidate, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> sendICECandidateAsync(String from, String to, String candidate)
    {
        return _iceI_sendICECandidateAsync(from, to, candidate, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> sendICECandidateAsync(String from, String to, String candidate, java.util.Map<String, String> context)
    {
        return _iceI_sendICECandidateAsync(from, to, candidate, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_candidate -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_sendICECandidateAsync(String iceP_from, String iceP_to, String iceP_candidate, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendICECandidate", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_candidate);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default Response endCall(String from, String to)
    {
        return endCall(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response endCall(String from, String to, java.util.Map<String, String> context)
    {
        return _iceI_endCallAsync(from, to, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> endCallAsync(String from, String to)
    {
        return _iceI_endCallAsync(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> endCallAsync(String from, String to, java.util.Map<String, String> context)
    {
        return _iceI_endCallAsync(from, to, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_endCallAsync(String iceP_from, String iceP_to, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                 }, istr -> {
                     Response ret;
                     ret = Response.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatServicePrx ice_adapterId(String newAdapterId)
    {
        return (ChatServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatServicePrx ice_connectionCached(boolean newCache)
    {
        return (ChatServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_secure(boolean b)
    {
        return (ChatServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_preferSecure(boolean b)
    {
        return (ChatServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatServicePrx ice_collocationOptimized(boolean b)
    {
        return (ChatServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatServicePrx ice_twoway()
    {
        return (ChatServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_oneway()
    {
        return (ChatServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_batchOneway()
    {
        return (ChatServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_datagram()
    {
        return (ChatServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_batchDatagram()
    {
        return (ChatServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatServicePrx ice_compress(boolean co)
    {
        return (ChatServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatServicePrx ice_timeout(int t)
    {
        return (ChatServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatServicePrx ice_connectionId(String connectionId)
    {
        return (ChatServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Chat::ChatService";
    }
}
