//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public class Message implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String from;

    public String to;

    public String content;

    public long timestamp;

    public boolean isGroup;

    public Message()
    {
        this.from = "";
        this.to = "";
        this.content = "";
    }

    public Message(String from, String to, String content, long timestamp, boolean isGroup)
    {
        this.from = from;
        this.to = to;
        this.content = content;
        this.timestamp = timestamp;
        this.isGroup = isGroup;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Message r = null;
        if(rhs instanceof Message)
        {
            r = (Message)rhs;
        }

        if(r != null)
        {
            if(this.from != r.from)
            {
                if(this.from == null || r.from == null || !this.from.equals(r.from))
                {
                    return false;
                }
            }
            if(this.to != r.to)
            {
                if(this.to == null || r.to == null || !this.to.equals(r.to))
                {
                    return false;
                }
            }
            if(this.content != r.content)
            {
                if(this.content == null || r.content == null || !this.content.equals(r.content))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                return false;
            }
            if(this.isGroup != r.isGroup)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Chat::Message");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, from);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, to);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, content);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isGroup);
        return h_;
    }

    public Message clone()
    {
        Message c = null;
        try
        {
            c = (Message)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.from);
        ostr.writeString(this.to);
        ostr.writeString(this.content);
        ostr.writeLong(this.timestamp);
        ostr.writeBool(this.isGroup);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.from = istr.readString();
        this.to = istr.readString();
        this.content = istr.readString();
        this.timestamp = istr.readLong();
        this.isGroup = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Message v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Message ice_read(com.zeroc.Ice.InputStream istr)
    {
        Message v = new Message();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Message> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Message v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Message> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Message.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Message _nullMarshalValue = new Message();

    /** @hidden */
    public static final long serialVersionUID = -1613508490L;
}
